name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: swa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4

      - name: Check SWA token presence
        run: |
          if [ -n "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then echo SET; else echo MISSING; exit 1; fi

      - name: Token length + hash (no leak)
        env: { SWA_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} }
        run: |
          echo "len=${#SWA_TOKEN}"
          python3 - << 'PY'
import os,hashlib
t=os.environ['SWA_TOKEN'].encode()
print("sha256="+hashlib.sha256(t).hexdigest())
PY

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"
          skip_app_build: true
          skip_api_build: true
